spring:
  profiles:
    active: local
    group:
      local:
        - local
      dev:
        - dev
      prod:
        - prod
  mvc:
    problemdetails:
      enabled: true
  data:
    jpa:
      repositories:
        enabled: false