spring:
  datasource:
    hikari:
      username: sa
      password: sa
      jdbc-url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
user:
  max-un-modify-password-duration: 360d
  userExpireDuration: 360d